version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - zid-dev-net
    depends_on:
      - postgres
    command: npm run start:debug
    environment:
      WAIT_HOSTS: postgres:5432

  postgres:
    container_name: postgres
    image: postgis/postgis
    env_file:
      - .env
    networks:
      - zid-dev-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PGDATA: /data/postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/data/postgres
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
  storage:
    image: ghcr.io/openzipkin/zipkin-mysql
    container_name: mysql
  adminer:
    image: adminer
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_HOST: ${DB_HOST}
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8080:9000
networks:
  zid-dev-net:
    driver: bridge
volumes:
  pgdata:
