FROM node:16-alpine as development

WORKDIR /usr/src/app

RUN apk --no-cache add --virtual .builds-deps build-base python3 \
    && npm install bcrypt node-gyp 

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait    

COPY package*.json ./

RUN npm install

COPY . .

CMD /wait