version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - zid-dev-net
    depends_on:
      - postgres
      - redis
    command: npm run start:dev
    environment:
      WAIT_HOSTS: postgres:5432

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    networks:
      - zid-dev-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  zid-dev-net:
    driver: bridge
volumes:
  pgdata:
